# Generated by Django 4.2.7 on 2026-10-07 07:32

import core.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Upload payment proof (receipt, screenshot, etc.)', null=True, upload_to='payment_proofs/', validators=[core.validators.validate_supporting_file]),
        ),
        migrations.AlterField(
            model_name='paymentaudit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
