# Generated by Django 4.2.7 on 2026-10-07 07:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent amount (frozen at lease creation)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('unit',), name='unique_active_lease_per_unit'),
        ),
    ]
