# Generated by Django 4.2.7 on 2026-01-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('repairs', 'Repairs'), ('electricity', 'Electricity'), ('water', 'Water'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('taxes', 'Property Taxes'), ('salaries', 'Salaries/Wages'), ('security', 'Security Services'), ('cleaning', 'Cleaning Services'), ('legal', 'Legal Fees'), ('marketing', 'Marketing/Advertising'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the expense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(help_text='Date expense was incurred')),
                ('receipt', models.FileField(blank=True, help_text='Upload receipt or supporting document', null=True, upload_to='expense_receipts/')),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor/supplier name', max_length=255)),
                ('vendor_contact', models.CharField(blank=True, help_text='Vendor contact', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_property', models.ForeignKey(blank=True, help_text='Associated property (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='properties.property')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.landlordprofile')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
