# Generated by Django 4.2.7 on 2026-01-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Reminder title/summary', max_length=255)),
                ('description', models.TextField(help_text='Detailed description')),
                ('reminder_date', models.DateField(help_text='Date to send reminder')),
                ('reminder_time', models.TimeField(default='09:00:00', help_text='Time to send reminder')),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', help_text='How often this reminder repeats', max_length=20)),
                ('send_sms', models.BooleanField(default=True, help_text='Send SMS notification')),
                ('send_email', models.BooleanField(default=True, help_text='Send email notification')),
                ('is_active', models.BooleanField(default=True, help_text='Active reminders will be sent')),
                ('last_sent', models.DateTimeField(blank=True, help_text='Last time reminder was sent', null=True)),
                ('next_send_date', models.DateField(blank=True, help_text='Next scheduled send date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.landlordprofile')),
                ('reminder_property', models.ForeignKey(blank=True, help_text='Associated property (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='properties.property')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'reminders',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
    ]
