# Generated by Django 4.2.7 on 2026-01-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Property name or building name', max_length=255)),
                ('location', models.CharField(help_text='Physical location/address', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.landlordprofile')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='Unit number or identifier', max_length=50)),
                ('unit_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('1bedroom', '1 Bedroom'), ('2bedroom', '2 Bedroom'), ('3bedroom', '3 Bedroom'), ('studio', 'Studio'), ('shop', 'Shop'), ('office', 'Office'), ('other', 'Other')], max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Base monthly rent amount', max_digits=10)),
                ('garbage_fee', models.DecimalField(decimal_places=2, default=0, help_text='Monthly garbage collection fee', max_digits=10)),
                ('water_billing_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('metered', 'Metered'), ('included', 'Included in Rent')], default='fixed', max_length=20)),
                ('water_fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly water charge', max_digits=10)),
                ('water_rate_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Rate per cubic meter if metered', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['unit_number'],
                'unique_together': {('unit_property', 'unit_number')},
            },
        ),
    ]
