# Generated by Django 4.2.7 on 2026-01-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('billing_month', models.DateField(help_text='Month being billed (first day of month)')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Monthly rent charge', max_digits=10)),
                ('water_amount', models.DecimalField(decimal_places=2, default=0, help_text='Water charge for the month', max_digits=10)),
                ('garbage_amount', models.DecimalField(decimal_places=2, default=0, help_text='Garbage collection fee', max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, help_text='Any other charges (repairs, penalties, etc.)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Total invoice amount', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid against this invoice', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('water_meter_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Current meter reading', max_digits=10, null=True)),
                ('previous_meter_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Previous meter reading', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or descriptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants_mgmt.lease')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-billing_month', '-created_at'],
                'unique_together': {('lease', 'billing_month')},
            },
        ),
    ]
