# Generated by Django 4.2.7 on 2026-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other charges (repairs, penalties, etc.)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='previous_meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='water_meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
