# Generated by Django 4.2.7 on 2026-10-07 07:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_invoice_notes_alter_invoice_other_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid against this invoice', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='garbage_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Garbage collection fee', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other charges (repairs, penalties, etc.)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent charge', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='water_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Water charge for the month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='invoice_amount_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('rent_amount__gte', 0), ('water_amount__gte', 0), ('garbage_amount__gte', 0), ('other_charges__gte', 0)), name='invoice_charges_nonnegative'),
        ),
    ]
